sudo: required
dist: xenial
language: bash
before_script:
- sudo apt-get update -qq
- sudo apt-get install make curl zip unzip check -qq
script:
- make
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: VD2eDycCvIlmZJLRlxKg86cf7m7lWaqqj8zPzjoULOBPCBh3x7qxqGMzjYEu33hnVwhnhdWd6utH4ZePY8q5rlvqxa521gE5WHpLTRhfjoQRwb9MkKfYWtgpol1P/OtjPOY8b29+L9ih9QQvS4FoOttJGPpDCwTzXLo2ajUP/9ZLyulL2J+9TAm3p0AZ8QFSwlIo+dIdZPQrjAYy7mkZIqDEORssoubDxcTK8aFZXZPscY2/uFoePWwBxaxxUKyBjn5WOCpAiZdOvI13PPuzi/3zJgw5X8l0JzancF75EZVVDugkrl4kLIwG5+RCHTm7N8feKzWuMEhfF1Ts2Qp5iHOu2cW1fm0CSLR1Cz6FZwRByNEe4x9YtV2XqDjCZGsL6APFBMCkAGRXTL9gUNWPWvIQJYkuYeYPSFauCUeu6WxOTTnNiXn9WH/2o7Qwm6wKs4geAro22QnNLEl5ELj6GBvF4LlKpOWn1nD4y/xs/vGWkO/cdQIFJ67r5sb52sIz3YN4KmRCUyVM4SwicRUvTFgwh3gNhcnyIEY9cq8x0jWW6bBwmnIHjYSuZpICIls8wsU8VmIVy/BhH/wwWYB/9Uh2gu5krOiVg4rpA5QMBkRINCnTpbcR/cTIGUzk0itZDhsq9OSsxOw0UJ2MMQr+UV0kGv/pKfAybL1rI+rvVxw=
  file: Void.zip
  on:
    repo: am11/VoidWSL
    tags: true
    all_branches: true
  skip_cleanup: true
