name: Main CI Workflow

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cleanup
        run: sudo rm -rf "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"
      - name: Install prerequisites
        run: sudo apt install make curl zip unzip check -qq
      - name: Build
        run: make
      - name: Get current date
        id: date
        run: echo "time=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.time }}
          name: nightly-release-${{ env.time }}
          body: |
            Void.zip built on ${{ env.time }}
          files: |
            Void.zip
                                      
